server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mariavanesalopez/spring-cloud-config-server.git
#          default-label: master
#          search-paths: caja


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      instance:
        hostname: localhost
management:
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info


